2023-09-12 10:37:16,541 INFO: Microblog startup [in /Users/pandysudhan/dev/flask/irisflower/app/__init__.py:32]
2023-09-12 10:37:56,870 INFO: Microblog startup [in /Users/pandysudhan/dev/flask/irisflower/app/__init__.py:32]
2023-09-12 10:38:39,776 INFO: Microblog startup [in /Users/pandysudhan/dev/flask/irisflower/app/__init__.py:32]
2023-09-12 10:39:55,554 INFO: Microblog startup [in /Users/pandysudhan/dev/flask/irisflower/app/__init__.py:32]
2023-09-13 09:02:24,115 INFO: Microblog startup [in /Users/pandysudhan/dev/flask/irisflower/app/__init__.py:32]
2023-09-13 09:38:05,611 INFO: Microblog startup [in /Users/pandysudhan/dev/flask/irisflower/app/__init__.py:32]
2023-09-13 09:38:20,780 INFO: Microblog startup [in /Users/pandysudhan/dev/flask/irisflower/app/__init__.py:32]
2023-09-13 09:39:19,807 INFO: Microblog startup [in /Users/pandysudhan/dev/flask/irisflower/app/__init__.py:32]
2023-09-13 09:39:32,212 INFO: Microblog startup [in /Users/pandysudhan/dev/flask/irisflower/app/__init__.py:32]
2023-09-13 09:41:59,371 INFO: Microblog startup [in /Users/pandysudhan/dev/flask/irisflower/app/__init__.py:32]
2023-09-13 09:44:08,828 INFO: Microblog startup [in /Users/pandysudhan/dev/flask/irisflower/app/__init__.py:32]
2023-09-13 09:45:31,421 INFO: Microblog startup [in /Users/pandysudhan/dev/flask/irisflower/app/__init__.py:32]
2023-09-13 09:45:34,416 ERROR: Exception on /4.7,3.2,1.2,0.2 [GET] [in /Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pandysudhan/dev/flask/irisflower/app/routes.py", line 8, in get
    features = int(features.split(','))
               ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'
2023-09-13 09:45:37,398 ERROR: Exception on /4.7,3.2,1.2,0.2 [GET] [in /Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pandysudhan/dev/flask/irisflower/app/routes.py", line 8, in get
    features = int(features.split(','))
               ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'
2023-09-13 09:45:38,078 ERROR: Exception on /4.7,3.2,1.2,0.2 [GET] [in /Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pandysudhan/dev/flask/irisflower/app/routes.py", line 8, in get
    features = int(features.split(','))
               ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'
2023-09-13 09:45:38,673 ERROR: Exception on /4.7,3.2,1.2,0.2 [GET] [in /Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pandysudhan/dev/flask/irisflower/app/routes.py", line 8, in get
    features = int(features.split(','))
               ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'
2023-09-13 09:46:22,405 INFO: Microblog startup [in /Users/pandysudhan/dev/flask/irisflower/app/__init__.py:32]
2023-09-13 09:46:26,752 ERROR: Exception on /4.7,3.2,1.2,0.2 [GET] [in /Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pandysudhan/dev/flask/irisflower/venv/lib/python3.11/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pandysudhan/dev/flask/irisflower/app/routes.py", line 10, in get
    features[i] = int(features[i])
                  ^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '4.7'
